### ISSUE TITLE
Read at browser: RangeError

### ISSUE THREAD

**Issue by botika** [jdiaz5513/capnp-ts#100]
To the read message with the following code:
```
const data = new Message(arrayBuffer);
console.log(data.getRoot(Msg));
```
It returns the following error:
`RangeError: offset is outside the bounds of the DataView` with end at segment.js:197

Tested with: 
`Chromium 68.0.3440.106 Arch Linux`
`Mozilla Firefox 61.0.2`

you do not have any template of issues, if you need more information just comment it.

**Comment by leapfrog-saugat** [comment]
I have the exact issue. I am trying to read a Capnp message sent by server written in Cpp but getting the same error.

**Comment by leapfrog-saugat** [comment]
I am not getting any error now by settingingleSegment flag to true in capnp.Message method. I assume the message I am getting from the server doesn't have framing header. Updated code below.
```
const reader = new FileReader();
      reader.readAsArrayBuffer(message.data);
      reader.onloadend = () => {
        const capnpMessageArrBuff = new capnp.Message(reader.result, true, true);
        const sessionProcessingState = capnpMessageArrBuff.getRoot(portalSchema.GetSessionProcessingStateResponse);
       }
```

The second parameter in capnp.Message is for setting packedMessage = true. The third parameter is for setting singSegment = true.

**Comment by leapfrog-saugat** [comment]
@botika Did you solve the issue?

**Comment by botika** [comment]
I'm sorry but change the whole implementation to JSON. This weekend I will rebuild it again. I'm sorry for the delay.

**Comment by botika** [comment]
Now it does not give that error, but the message after serializing remains empty. That is, if `msg.getName()` the resulting string is empty. But the testing with `reader.readAsStringBytes()`, you can see the name, so the message is correct. My structure `{ name: Text, payload: List (Another)}`

**Comment by fasterthanlime** [comment]
This can probably be closed if it's not active anymore?

I'll just chime in: I did get similar error message when first playing with serialization/deserialization over a stream. Some cap'n proto implementations (like the capnproto-go2 RPC implementation) default to the "unpacked" format, whereas Message's constructor defaults to packed:

https://github.com/jdiaz5513/capnp-ts/blob/1ace2aebdbfbedb6ef960dd07f4f3688f4e51b25/packages/capnp-ts/src/serialization/message.ts#L77-L81

I'd say that this error message is *usually* caused by calling `new Message(arrayBuffer)` instead of `new Message(arrayBuffer, false /* packed */)`. I find the default a bit odd, but it might be too late to change?

**Comment by botika** [comment]
closed, thanks
