### ISSUE TITLE
Convert `capnpc` trace identifier to `capnpc-ts`

### ISSUE THREAD

**Issue by efokschaner** [jdiaz5513/capnp-ts#42]
I'm introducing `capnpc-js` as a tracing identifier, so it would seem natural to make the other one match its package name.

**Comment by jdiaz5513** [comment]
In practice (in **very** large projects) I've seen the mess that happens when you have too granular trace/log identifiers.

In fact, there's a good argument to just have one `capnp` trace identifier for the whole library and `capnpc` for the compiler, considering it will be used in the future for bug reports and we'll want to capture as much detail as possible. That was the primary intent for including trace messages to begin with.

**Comment by efokschaner** [comment]
In that case, would you prefer capnpc-js to use capnpc too?

**Comment by jdiaz5513** [comment]
Yes. :+1:
