### ISSUE TITLE
Pointer._validate is too eager and too strict

### ISSUE THREAD

**Issue by efokschaner** [jdiaz5513/capnp-ts#46]
So I discovered this purely by luck.
When I run capnpc-ts it runs into this error:
```
Error: CAPNP-TS028 Attempted to convert CodeGeneratorRequest_Struct_Pointer_0@0x00000000,[00 00 00 00 00 00 02 00],limit:0x7fffffff to a struct with the wrong pointer size (found: 3).
    at CodeGeneratorRequest.Pointer._validate (/Users/efokschaner/dev/efokschaner/capnp-ts/packages/capnp-ts/lib/serialization/pointers/pointer.js:539:35)
```
From https://github.com/jdiaz5513/capnp-ts/blob/b5cb174a990c5fb45288289bceaf17362c19b778/packages/capnp-ts/src/serialization/pointers/pointer.ts#L831

So I've figured out why:
A few weeks ago when starting work on this I ran `brew install capnp`. At that time I received capnp v0.5.3. The latest version which came out in the last few months is v0.6.0. Between those versions a `capnpVersion` member was added to `CodeGeneratorRequest`. Our `_validate` check fails because I'm feeding in an object with 2 pointers when the schema described 3.

Now the capnproto docs don't state anywhere (as far as i could see) what the correct behaviour should be under exactly this circumstance. There's stuff about default values, and there's even some good discussion about what should happen when a "client fails to set a particular field" (see https://capnproto.org/faq.html#how-do-i-make-a-field-required-like-in-protocol-buffers) where you could imagine "Failing to set" being the same as "Used an older schema and therefore didn't set".

If I understand correctly, one of capnproto's design goals is to only perform validation once its needed to access so that "you only pay for what you use". Another goal is to provide flexible yet predictable backwards compatibility, either when newer messages are interpreted via older schemas, OR when older messages are interpreted via newer schemas. 

I'm still digging around the C++ version to see what the implementation-defined specification is for this scenario.

So far, it seems to me that the right interpretation is that on the receiving side, deserialization is valid and it should be as if the value was the default (either the implicit or explicit default if an explicit default was made for the field). Let me know if you agree / disagree, or if you can find any more concrete information about this scenario.

I also want to ask if you're aware of anywhere else in the library currently that might also be too strict or eager in its validation like this?

So I'll probably unblock myself for now by upgrading to capnp 0.6.0, but this has given me some good ideas for some end to end tests around producers and consumers with different (but compatible) schemas on the next iteration :)

**Comment by jdiaz5513** [comment]
This is a great find, and definitely one of the rough patches of the implementation (precisely because of the ambiguity in the spec).

I'm working on Pointer test coverage right now, will give this a very careful look.

Chances are I just need to relax the check.

I'm less concerned about the eagerness because premature optimization is evil and all that, but still keeping it in mind since you are right that it _is_ one of the design goals to be as frugal as possible while still staying safe.

**Comment by kentonv** [comment]
Any struct received on the wire -- regardless of its section sizes -- is a valid match for any defined struct schema. If a section is larger than the reader expected, the reader should ignore trailing words/pointers. If the section is shorter than expected, the reader should treat the missing words/pointers as if they were zero/null. (Note that because data values are XOR'd with their defaults on read/write, and a null pointer is treated equivalent to its default value, treating the missing data as zero/null is equivalent to treating it as the default value.)

This is necessary to support the evolution properties described here: https://capnproto.org/language.html#evolving-your-protocol

Specifically, if a struct was constructed using an older version of the protocol, it may be missing newly-added fields, making the sections shorter than expected. If it was constructed using a newer version, it may have set new fields that the reader doesn't know about, making the sections larger than expected.

Of course, for zero-copy operation, you don't want to have to resize structs that came off the wire smaller than expected. So, on the reader side, the getter methods for each field will probably need to check if the field offset is out-of-range for the underlying section, and return the default value if so.

Also note that it's important to preserve data you don't understand when copying a struct from a Reader into a Builder. An intermediate server that processes and forwards messages should not silently drop data it doesn't understand.

To that end, copying data from a Reader to a Builder should be implemented in a schema-agnostic fashion. It's possible to perform a deep copy using only the metadata available in the pointers as encoded on the wire.

This leads to a possible problem: What if you copy a struct from a Reader to a Builder, but the struct is smaller than its schema expects, and then the application attempts to access and modify that struct, modifying fields that are out-of-bounds? Since the copying is done schema-agnostic, you can't guarantee that the struct will be big enough.

To solve this, in the C++ code, when the application tries to get a struct builder, and the underlying pointer indicates the struct is smaller than expected, the code makes a new properly-sized shallow copy of the struct, and updates the pointer to point at that. (This leaves a "hole" in the message of bytes which waste space but carry no data, which is unfortunate, but at least the hole is zero'd, so it should pack well.) Note that this copy should never reduce the size of the struct, only increase, because, again, you don't want to discard trailing data you don't understand.

I guess I should integrate this into the capnp docs...

**Comment by efokschaner** [comment]
@kentonv  thanks, having this in the docs would be v helpful to implementers in other languages.
