### ISSUE TITLE
capnp imports in JS

### ISSUE THREAD

**Issue by smoreinis** [jdiaz5513/capnp-ts#88]
This is basically a continuation of https://github.com/jdiaz5513/capnp-ts/issues/75 - at this point, generating the TS files for foo.capnp referenced in the issue works but generating JS files fails with
```
foo.capnp.ts:9:21 Cannot find module './bar.capnp'.
foo.capnp.ts:9:21 Cannot find module './bar.capnp'.
Error: CAPNPC-TS008 Failed to transpile emitted schema source code; see above for error messages.
    at transpileAll (/usr/local/lib/node_modules/capnpc-js/lib/index.js:71:15)
```

Is there another way to make this work or a JS implementation oversight?

**Comment by jdiaz5513** [comment]
This is a bit tricky - the typescript compiler requires all imports to be valid so that means `bar.capnp.ts` needs to be emitted before `foo.capnp.js` is transpiled.

You can get around this by either compiling all the schema files at once (`capnpc -ojs src/capnp/*.capnp`) or by compiling `bar.capnp` first.

`noEmitOnError: false` might help here, leaving this issue open to remind me to try that.

**Comment by smoreinis** [comment]
Compiling `bar.capnp` first and then compiling `foo.capnp` gets me:
```
foo.capnp.ts:9:21 Could not find a declaration file for module './bar.capnp'. '/Users/stas/test/bar.capnp.js' implicitly has an 'any' type.
foo.capnp.ts:9:21 Could not find a declaration file for module './bar.capnp'. '/Users/stas/test/bar.capnp.js' implicitly has an 'any' type.
```
Is there something else that needs to be done to make that work?

Compiling all the schema files at once seems to work though, thanks!
